export default {
  PAY_AS_GUEST: 'PAY_AS_GUEST',
  GIFTBACK_COMPLETE: 'GIFTBACK_COMPLETE',
  GIFTBACK_INACTIVE: 'GIFTBACK_INACTIVE',
  GIFTBACK_APPLY: 'GIFTBACK_APPLY,',
  PAYMENT_STATUS: 'PAYMENT_STATUS',
};
