name: Tag Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - name: Create .env file
        run: |
          cat <<EOF > .env
          NODE_ENV=production
          OPENPIX_PLUGIN_URL=https://plugin.openpix.com.br/v1/openpix.js
          SVN_USERNAME=${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD=${{ secrets.SVN_PASSWORD }}
          SVN_REPO_URL=${{ secrets.SVN_REPO_URL }}
          GITHUB_API_TOKEN=${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          EOF
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: pnpm es ./scripts/svn-release.ts
